// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS5UK2LJeCEe6Zx1KVsoOY4YnVlK-LVK8',
    appId: '1:370990706310:web:23af4ce1733cbf9fa9eb07',
    messagingSenderId: '370990706310',
    projectId: 'hackathon-caf6b',
    authDomain: 'hackathon-caf6b.firebaseapp.com',
    storageBucket: 'hackathon-caf6b.appspot.com',
    measurementId: 'G-L9S60HZBH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WL9V7EBZd3QwVcJNKA8B9wWcuY_FkfU',
    appId: '1:370990706310:android:7d963f0aedc2b416a9eb07',
    messagingSenderId: '370990706310',
    projectId: 'hackathon-caf6b',
    storageBucket: 'hackathon-caf6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8eN4PiQHXhUUKv6mLry7prsPAFNGuwC8',
    appId: '1:370990706310:ios:6f78e6f29032ae29a9eb07',
    messagingSenderId: '370990706310',
    projectId: 'hackathon-caf6b',
    storageBucket: 'hackathon-caf6b.appspot.com',
    iosClientId: '370990706310-iqd26173vgq0j7chgaigta37i6ihukve.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8eN4PiQHXhUUKv6mLry7prsPAFNGuwC8',
    appId: '1:370990706310:ios:cae3606359d8e6cca9eb07',
    messagingSenderId: '370990706310',
    projectId: 'hackathon-caf6b',
    storageBucket: 'hackathon-caf6b.appspot.com',
    iosClientId: '370990706310-fravi2iu2je873glum3m2qshup0ph82j.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon.RunnerTests',
  );
}
